[PKGBUILD] linux-aarch64-rpi: Don't build the Rockchip ISP v1 media driver
The driver seems to need adjustments due to possible changes to V4L2 in the
Raspberry Pi tree (though this is just a random thought) and fails to build
in it's current state. So, deselect CONFIG_VIDEO_ROCKCHIP_ISP1. Since the
resulting package is intended for use on the Raspberry Pi platform, this
shouldn't really matter.

Fixes:

  CC [M]  drivers/media/platform/rockchip/rkisp1/rkisp1-isp.o
  CC [M]  drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.o
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c: In function 'rkisp1_isp_get_pad_fmt':
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:217:34: error: redefinition of 'state'
  217 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:214:34: note: previous definition of 'state' with type 'struct v4l2_subdev_state'
  214 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:218:25: error: initialization of 'struct v4l2_subdev_pad_config *' from incompatible pointer type 'struct v4l2_subdev_state *' [-Werror=incompatible-pointer-types]
  218 |                 .pads = &state
      |                         ^
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:218:25: note: (near initialization for 'state.pads')
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:220:34: error: redefinition of 'state'
  220 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:217:34: note: previous definition of 'state' with type 'struct v4l2_subdev_state'
  217 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:221:25: error: initialization of 'struct v4l2_subdev_pad_config *' from incompatible pointer type 'struct v4l2_subdev_state *' [-Werror=incompatible-pointer-types]
  221 |                 .pads = &state
      |                         ^
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:221:25: note: (near initialization for 'state.pads')
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c: In function 'rkisp1_isp_get_pad_crop':
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:237:34: error: redefinition of 'state'
  237 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:234:34: note: previous definition of 'state' with type 'struct v4l2_subdev_state'
  234 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:238:25: error: initialization of 'struct v4l2_subdev_pad_config *' from incompatible pointer type 'struct v4l2_subdev_state *' [-Werror=incompatible-pointer-types]
  238 |                 .pads = &state
      |                         ^
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:238:25: note: (near initialization for 'state.pads')
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:240:34: error: redefinition of 'state'
  240 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:237:34: note: previous definition of 'state' with type 'struct v4l2_subdev_state'
  237 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:241:25: error: initialization of 'struct v4l2_subdev_pad_config *' from incompatible pointer type 'struct v4l2_subdev_state *' [-Werror=incompatible-pointer-types]
  241 |                 .pads = &state
      |                         ^
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:241:25: note: (near initialization for 'state.pads')
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c: In function 'rkisp1_isp_register':
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:1081:34: error: redefinition of 'state'
 1081 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:1078:34: note: previous definition of 'state' with type 'struct v4l2_subdev_state'
 1078 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:1082:25: error: initialization of 'struct v4l2_subdev_pad_config *' from incompatible pointer type 'struct v4l2_subdev_state *' [-Werror=incompatible-pointer-types]
 1082 |                 .pads = &state
      |                         ^
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:1082:25: note: (near initialization for 'state.pads')
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:1084:34: error: redefinition of 'state'
 1084 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:1081:34: note: previous definition of 'state' with type 'struct v4l2_subdev_state'
 1081 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:1085:25: error: initialization of 'struct v4l2_subdev_pad_config *' from incompatible pointer type 'struct v4l2_subdev_state *' [-Werror=incompatible-pointer-types]
 1085 |                 .pads = &state
      |                         ^
drivers/media/platform/rockchip/rkisp1/rkisp1-isp.c:1085:25: note: (near initialization for 'state.pads')
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:288: drivers/media/platform/rockchip/rkisp1/rkisp1-isp.o] Error 1
make[4]: *** Waiting for unfinished jobs....
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c: In function 'rkisp1_rsz_get_pad_fmt':
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:189:34: error: redefinition of 'state'
  189 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:186:34: note: previous definition of 'state' with type 'struct v4l2_subdev_state'
  186 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:190:25: error: initialization of 'struct v4l2_subdev_pad_config *' from incompatible pointer type 'struct v4l2_subdev_state *' [-Werror=incompatible-pointer-types]
  190 |                 .pads = &state
      |                         ^
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:190:25: note: (near initialization for 'state.pads')
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:192:34: error: redefinition of 'state'
  192 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:189:34: note: previous definition of 'state' with type 'struct v4l2_subdev_state'
  189 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:193:25: error: initialization of 'struct v4l2_subdev_pad_config *' from incompatible pointer type 'struct v4l2_subdev_state *' [-Werror=incompatible-pointer-types]
  193 |                 .pads = &state
      |                         ^
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:193:25: note: (near initialization for 'state.pads')
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c: In function 'rkisp1_rsz_get_pad_crop':
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:209:34: error: redefinition of 'state'
  209 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:206:34: note: previous definition of 'state' with type 'struct v4l2_subdev_state'
  206 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:210:25: error: initialization of 'struct v4l2_subdev_pad_config *' from incompatible pointer type 'struct v4l2_subdev_state *' [-Werror=incompatible-pointer-types]
  210 |                 .pads = &state
      |                         ^
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:210:25: note: (near initialization for 'state.pads')
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:212:34: error: redefinition of 'state'
  212 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:209:34: note: previous definition of 'state' with type 'struct v4l2_subdev_state'
  209 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:213:25: error: initialization of 'struct v4l2_subdev_pad_config *' from incompatible pointer type 'struct v4l2_subdev_state *' [-Werror=incompatible-pointer-types]
  213 |                 .pads = &state
      |                         ^
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:213:25: note: (near initialization for 'state.pads')
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c: In function 'rkisp1_rsz_register':
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:806:34: error: redefinition of 'state'
  806 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:803:34: note: previous definition of 'state' with type 'struct v4l2_subdev_state'
  803 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:807:25: error: initialization of 'struct v4l2_subdev_pad_config *' from incompatible pointer type 'struct v4l2_subdev_state *' [-Werror=incompatible-pointer-types]
  807 |                 .pads = &state
      |                         ^
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:807:25: note: (near initialization for 'state.pads')
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:809:34: error: redefinition of 'state'
  809 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:806:34: note: previous definition of 'state' with type 'struct v4l2_subdev_state'
  806 |         struct v4l2_subdev_state state = {
      |                                  ^~~~~
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:810:25: error: initialization of 'struct v4l2_subdev_pad_config *' from incompatible pointer type 'struct v4l2_subdev_state *' [-Werror=incompatible-pointer-types]
  810 |                 .pads = &state
      |                         ^
drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.c:810:25: note: (near initialization for 'state.pads')
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:288: drivers/media/platform/rockchip/rkisp1/rkisp1-resizer.o] Error 1
make[3]: *** [scripts/Makefile.build:550: drivers/media/platform/rockchip/rkisp1] Error 2
make[2]: *** [scripts/Makefile.build:550: drivers/media/platform] Error 2
make[1]: *** [scripts/Makefile.build:550: drivers/media] Error 2